function modelPath = create_icare_simulink_demo(imagePath)
%CREATE_ICARE_SIMULINK_DEMO Build a Simulink demo model for ICare inference.
addpath(genpath(fullfile(fileparts(mfilename("fullpath")), "..")));

if nargin < 1 || strlength(string(imagePath)) == 0
    imagePath = default_demo_image();
end

imagePath = char(string(imagePath));
if ~isfile(imagePath)
    error("ICare:Simulink:MissingImage", "Demo image not found: %s", imagePath);
end

projectRoot = fullfile(fileparts(mfilename("fullpath")), "..", "..");
modelDir = fullfile(projectRoot, "simulink");
if ~isfolder(modelDir)
    mkdir(modelDir);
end

modelName = "ICare_Simulink_Demo";
modelPath = fullfile(modelDir, modelName + ".slx");

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

new_system(modelName);
cleanup = onCleanup(@() close_if_loaded(modelName));

inferenceBlock = modelName + "/ICare Inference";
add_block("simulink/User-Defined Functions/MATLAB Function", inferenceBlock, ...
    "Position", [95 120 275 310]);
set_chart_script(inferenceBlock, imagePath);

labels = ["Status", "DR Grade", "Confidence %", "Review Flag", "Vessels %", ...
    "Hard Exudates %", "Microaneurysms %", "Haemorrhages %", "Soft Exudates %"];

for idx = 1:numel(labels)
    blockName = modelName + "/" + labels(idx);
    y = 15 + idx * 38;
    add_block("simulink/Sinks/Display", blockName, ...
        "Position", [400 y 530 y + 28], ...
        "NameLocation", "right");
    add_line(modelName, "ICare Inference/" + idx, labels(idx) + "/1", "autorouting", "on");
end

decisionBlock = modelName + "/Rural Bandwidth Decision";
add_block("simulink/User-Defined Functions/MATLAB Function", decisionBlock, ...
    "Position", [645 145 855 270]);
set_decision_chart_script(decisionBlock);

add_line(modelName, "ICare Inference/1", "Rural Bandwidth Decision/1", "autorouting", "on");
add_line(modelName, "ICare Inference/2", "Rural Bandwidth Decision/2", "autorouting", "on");
add_line(modelName, "ICare Inference/3", "Rural Bandwidth Decision/3", "autorouting", "on");
add_line(modelName, "ICare Inference/4", "Rural Bandwidth Decision/4", "autorouting", "on");

edgeLabels = ["Edge Mode", "Compact Packet KB", "Full Upload Flag", "Latency Saved s"];
for idx = 1:numel(edgeLabels)
    blockName = modelName + "/" + edgeLabels(idx);
    y = 115 + idx * 48;
    add_block("simulink/Sinks/Display", blockName, ...
        "Position", [980 y 1135 y + 30], ...
        "NameLocation", "right");
    add_line(modelName, "Rural Bandwidth Decision/" + idx, edgeLabels(idx) + "/1", "autorouting", "on");
end

set_param(modelName, "StopTime", "0");
set_param(modelName, "Solver", "FixedStepDiscrete");
save_system(modelName, modelPath);
close_system(modelName, 0);
delete(cleanup);

fprintf("Saved ICare Simulink demo model: %s\n", modelPath);
end

function imagePath = default_demo_image()
cfg = icare_config();
aptosTbl = read_aptos_dataset(cfg.dataRoot);
if isempty(aptosTbl)
    error("ICare:Simulink:NoImages", "No APTOS images found for the Simulink demo.");
end
imagePath = aptosTbl.imagePath(1);
end

function set_chart_script(blockPath, imagePath)
rt = sfroot;
chart = rt.find("-isa", "Stateflow.EMChart", "Path", blockPath);
if isempty(chart)
    error("ICare:Simulink:MissingChart", "Could not find MATLAB Function chart: %s", blockPath);
end

escapedPath = strrep(imagePath, "'", "''");
scriptTemplate = [ ...
    'function [statusCode, predictedGrade, confidencePct, reviewFlag, vesselPct, hardExudatePct, microaneurysmPct, haemorrhagePct, softExudatePct] = f()' newline ...
    '%%#codegen' newline ...
    'coder.extrinsic(''icare_simulink_predict'');' newline ...
    'statusCode = 0;' newline ...
    'predictedGrade = -1;' newline ...
    'confidence = 0;' newline ...
    'reviewFlag = 1;' newline ...
    'vesselFraction = NaN;' newline ...
    'hardExudateFraction = NaN;' newline ...
    'microaneurysmFraction = NaN;' newline ...
    'haemorrhageFraction = NaN;' newline ...
    'softExudateFraction = NaN;' newline ...
    '[statusCode, predictedGrade, confidence, reviewFlag, vesselFraction, hardExudateFraction, microaneurysmFraction, haemorrhageFraction, softExudateFraction] = icare_simulink_predict(''%s'');' newline ...
    'confidencePct = 100 * confidence;' newline ...
    'vesselPct = 100 * vesselFraction;' newline ...
    'hardExudatePct = 100 * hardExudateFraction;' newline ...
    'microaneurysmPct = 100 * microaneurysmFraction;' newline ...
    'haemorrhagePct = 100 * haemorrhageFraction;' newline ...
    'softExudatePct = 100 * softExudateFraction;' newline ...
    'end' newline];
chart.Script = sprintf(scriptTemplate, escapedPath);
end

function set_decision_chart_script(blockPath)
rt = sfroot;
chart = rt.find("-isa", "Stateflow.EMChart", "Path", blockPath);
if isempty(chart)
    error("ICare:Simulink:MissingChart", "Could not find MATLAB Function chart: %s", blockPath);
end

chart.Script = [ ...
    'function [edgeMode, compactPacketKB, fullUploadFlag, latencySavedSec] = f(statusCode, predictedGrade, confidencePct, reviewFlag)' newline ...
    '%%#codegen' newline ...
    '% Rural screening assumption: low bandwidth link at the camp.' newline ...
    'fullImageKB = 4096;' newline ...
    'compactPacketKB = 12;' newline ...
    'bandwidthKbps = 256;' newline ...
    'cloudRoundTripSec = 3;' newline ...
    'if statusCode < 1' newline ...
    '    edgeMode = 0;' newline ...
    '    fullUploadFlag = 0;' newline ...
    '    latencySavedSec = 0;' newline ...
    '    return;' newline ...
    'end' newline ...
    'highRisk = predictedGrade >= 2 || confidencePct < 50 || reviewFlag >= 1;' newline ...
    'if highRisk' newline ...
    '    edgeMode = 2;' newline ...
    '    fullUploadFlag = 1;' newline ...
    'else' newline ...
    '    edgeMode = 1;' newline ...
    '    fullUploadFlag = 0;' newline ...
    'end' newline ...
    'fullUploadSec = 8 * fullImageKB / bandwidthKbps + cloudRoundTripSec;' newline ...
    'compactUploadSec = 8 * compactPacketKB / bandwidthKbps + cloudRoundTripSec;' newline ...
    'latencySavedSec = fullUploadSec - compactUploadSec;' newline ...
    'end' newline];
end

function close_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
